"""Export service: CSV and JSON export of analysis results."""
import csv
import json
import io
from datetime import datetime


DISCLAIMER = "Generated by Coronary RWS Analyser v2.0 -- For Research Use Only. Not validated for clinical decision-making."


def export_csv(
    session_id: str,
    qca_results: dict[int, dict],
    rws_results: list[dict],
    anonymize: bool = True,
) -> str:
    """Export analysis results as CSV string."""
    output = io.StringIO()
    writer = csv.writer(output)

    # Header disclaimer
    writer.writerow([DISCLAIMER])
    writer.writerow([f"Session: {session_id}", f"Exported: {datetime.utcnow().isoformat()}"])
    writer.writerow([])

    # QCA Results
    if qca_results:
        writer.writerow(["QCA Results"])
        writer.writerow(["Frame", "MLD (mm)", "DS%", "Proximal Ref (mm)", "Distal Ref (mm)",
                         "Lesion Length (mm)", "Vessel Length (mm)", "Method", "Pixel Spacing (mm)"])
        for frame_idx, metrics in sorted(qca_results.items()):
            writer.writerow([
                frame_idx,
                metrics.get("mld_mm", ""),
                metrics.get("diameter_stenosis_pct", ""),
                metrics.get("proximal_ref_mm", ""),
                metrics.get("distal_ref_mm", ""),
                metrics.get("lesion_length_mm", ""),
                metrics.get("vessel_length_mm", ""),
                metrics.get("method", ""),
                metrics.get("pixel_spacing_mm", ""),
            ])
        writer.writerow([])

    # RWS Results
    if rws_results:
        writer.writerow(["RWS Results"])
        writer.writerow(["Start Frame", "End Frame", "MLD RWS%", "Proximal RWS%",
                         "Distal RWS%", "Average RWS%", "Interpretation", "Outlier Method", "Vessel"])
        for r in rws_results:
            writer.writerow([
                r.get("start_frame", ""),
                r.get("end_frame", ""),
                r.get("mld_rws_pct", ""),
                r.get("proximal_rws_pct", ""),
                r.get("distal_rws_pct", ""),
                r.get("average_rws_pct", ""),
                r.get("interpretation", ""),
                r.get("outlier_method", ""),
                r.get("vessel", ""),
            ])

    return output.getvalue()


def export_json(
    session_id: str,
    qca_results: dict[int, dict],
    rws_results: list[dict],
    anonymize: bool = True,
) -> str:
    """Export analysis results as JSON string."""
    data = {
        "disclaimer": DISCLAIMER,
        "session_id": session_id,
        "exported_at": datetime.utcnow().isoformat(),
        "qca_results": {str(k): v for k, v in qca_results.items()} if qca_results else {},
        "rws_results": rws_results or [],
    }
    return json.dumps(data, indent=2)
